baseURL: "https://den-bogdanov.github.io/"
title: "My Blog"
theme: PaperMod

pagination:
  pagerSize: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: My Blog
  description: "Welcome to my personal blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Your Name
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  profileMode:
    enabled: true
    title: "Your Name"
    subtitle: "Welcome to my blog!"
    imageUrl: "#" # Add your image URL here
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: About
        url: about

  socialIcons:
    - name: github
      # url: "https://github.com/yourusername"
    - name: twitter
      # url: "https://twitter.com/yourusername"
    - name: linkedin
      # url: "https://linkedin.com/in/yourusername"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url